AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Apache-Tomcat Server

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro


Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
        InstanceType: !Ref InstanceType
        SecurityGroups:
          - !Ref InstanceSecurityGroup
        KeyName: !Ref KeyName
        ImageId: ami-0aeeebd8d2ab47354
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash -xe
              sudo hostnamectl set-hostname tomcat.example.com
              sudo yum install java-1.8.0 -y
              cd /opt/
              sudo wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz
              sudo tar -zvxf apache-tomcat-9.0.35.tar.gz
              sudo ls -ltr /opt/apache-tomcat-9.0.35/bin
              sudo cd /opt/apache-tomcat-9.0.35/bin
              sudo chmod +x /opt/apache-tomcat-9.0.35/bin/startup.sh
              sudo chmod +x /opt/apache-tomcat-9.0.35/bin/shutdown.sh
              sudo ln -s /opt/apache-tomcat-9.0.35/bin/startup.sh /usr/bin/tomcatup
              sudo ln -s /opt/apache-tomcat-9.0.35/bin/shutdown.sh /usr/bin/tomcatdown
              tomcatup
              sudo yum install ruby -y
              sudo yum install wget -y
              wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
              chmod +x ./install
              sudo ./install auto
              sudo systemctl start codedeploy-agent
              sudo systemctl restart codedeploy-agent

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
        GroupDescription: Enable SSH access via port 22
        GroupName: Apache_Tomcat_SG
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: '8080'
            ToPort: '8080'
            CidrIp: 0.0.0.0/0